# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/u9510e/setup-DEVICEMAKEFILEs.sh

LOCAL_PATH := vendor/huawei/u9510e

PRODUCT_COPY_FILES += \
 $(LOCAL_PATH)/proprietary/system/isp.bin:system/isp.bin \
 $(LOCAL_PATH)/proprietary/system/ons.bin:system/ons.bin \
 $(LOCAL_PATH)/proprietary/system/app/DolbyMobileAudioEffectService.apk:system/app/DolbyMobileAudioEffectService.apk \
 $(LOCAL_PATH)/proprietary/system/app/HwGlobalDolbyEffect.apk:system/app/HwGlobalDolbyEffect.apk \
 $(LOCAL_PATH)/proprietary/system/bin/surfaceflinger:system/bin/surfaceflinger \
 $(LOCAL_PATH)/proprietary/system/bin/mediaserver:system/bin/mediaserver \
 $(LOCAL_PATH)/proprietary/system/bin/akm8975:system/bin/akm8975 \
 $(LOCAL_PATH)/proprietary/system/bin/akmd8963:system/bin/akmd8963 \
 $(LOCAL_PATH)/proprietary/system/bin/glgps:system/bin/glgps \
 $(LOCAL_PATH)/proprietary/system/bin/gpslogd:system/bin/gpslogd \
 $(LOCAL_PATH)/proprietary/system/bin/rild:system/bin/rild \
 $(LOCAL_PATH)/proprietary/system/bin/IMCdownload_App:system/bin/IMCdownload_App \
 $(LOCAL_PATH)/proprietary/system/bin/Injection_nv:system/bin/Injection_nv \
 $(LOCAL_PATH)/proprietary/system/bin/nvm_server:system/bin/nvm_server \
 $(LOCAL_PATH)/proprietary/system/bin/imc_poweron:system/bin/imc_poweron \
 $(LOCAL_PATH)/proprietary/system/bin/BCM4330B1.hcd:system/bin/BCM4330B1.hcd \
 $(LOCAL_PATH)/proprietary/system/bin/am:system/bin/am \
 $(LOCAL_PATH)/proprietary/system/bin/bmgr:system/bin/bmgr \
 $(LOCAL_PATH)/proprietary/system/bin/bu:system/bin/bu \
 $(LOCAL_PATH)/proprietary/system/bin/content:system/bin/content \
 $(LOCAL_PATH)/proprietary/system/bin/hostapd:system/bin/hostapd \
 $(LOCAL_PATH)/proprietary/system/bin/ime:system/bin/ime \
 $(LOCAL_PATH)/proprietary/system/bin/input:system/bin/input \
 $(LOCAL_PATH)/proprietary/system/bin/monkey:system/bin/monkey \
 $(LOCAL_PATH)/proprietary/system/bin/pcscd:system/bin/pcscd \
 $(LOCAL_PATH)/proprietary/system/bin/pm:system/bin/pm \
 $(LOCAL_PATH)/proprietary/system/bin/requestsync:system/bin/requestsync \
 $(LOCAL_PATH)/proprietary/system/bin/svc:system/bin/svc \
 $(LOCAL_PATH)/proprietary/system/bin/testpcsc:system/bin/testpcsc \
 $(LOCAL_PATH)/proprietary/system/bin/testpcsc_sendapdu:system/bin/testpcsc_sendapdu \
 $(LOCAL_PATH)/proprietary/system/bin/uiautomator:system/bin/uiautomator \
 $(LOCAL_PATH)/proprietary/system/bin/wl:system/bin/wl \
 $(LOCAL_PATH)/proprietary/system/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so \
 $(LOCAL_PATH)/proprietary/system/lib/libaudio-resampler.so:system/lib/libaudio-resampler.so \
 $(LOCAL_PATH)/proprietary/system/lib/libaudioflinger.so:system/lib/libaudioflinger.so \
 $(LOCAL_PATH)/proprietary/system/lib/libsurfaceflinger.so:system/lib/libsurfaceflinger.so \
 $(LOCAL_PATH)/proprietary/system/lib/libsurfaceflinger_client.so:system/lib/libsurfaceflinger_client.so \
 $(LOCAL_PATH)/proprietary/system/lib/liboverlay.so:system/lib/liboverlay.so \
 $(LOCAL_PATH)/proprietary/system/lib/libGAL.so:system/lib/libGAL.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmedia.so:system/lib/libmedia.so \
 $(LOCAL_PATH)/proprietary/system/lib/libGLSLC.so:system/lib/libGLSLC.so \
 $(LOCAL_PATH)/proprietary/system/lib/libgui.so:system/lib/libgui.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_8290.so:system/lib/lib_8290.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_g1.so:system/lib/lib_g1.so \
 $(LOCAL_PATH)/proprietary/system/lib/libk3jpeg.so:system/lib/libk3jpeg.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_ffmpeg.so:system/lib/lib_k3_ffmpeg.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_avc.so:system/lib/lib_k3_omx_avc.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_avcenc.so:system/lib/lib_k3_omx_avcenc.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_mpeg2.so:system/lib/lib_k3_omx_mpeg2.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_mpeg4.so:system/lib/lib_k3_omx_mpeg4.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_rv.so:system/lib/lib_k3_omx_rv.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_vc1.so:system/lib/lib_k3_omx_vc1.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omx_vp8.so:system/lib/lib_k3_omx_vp8.so \
 $(LOCAL_PATH)/proprietary/system/lib/lib_k3_omxcore.so:system/lib/lib_k3_omxcore.so \
 $(LOCAL_PATH)/proprietary/system/lib/libisdb_omxcore.so:system/lib/libisdb_omxcore.so \
 $(LOCAL_PATH)/proprietary/system/lib/libclcore.bc:system/lib/libclcore.bc \
 $(LOCAL_PATH)/proprietary/system/lib/libclcore_neon.bc:system/lib/libclcore_neon.bc \
 $(LOCAL_PATH)/proprietary/system/lib/libmrc_cg_postprocess.so:system/lib/libmrc_cg_postprocess.so \
 $(LOCAL_PATH)/proprietary/system/lib/libui.so:system/lib/libui.so \
 $(LOCAL_PATH)/proprietary/system/lib/libvpp.so:system/lib/libvpp.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_rawdec.so:system/lib/libstagefright_soft_rawdec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_mpeg4dec.so:system/lib/libstagefright_soft_mpeg4dec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_g711dec.so:system/lib/libstagefright_soft_g711dec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_mp3dec.so:system/lib/libstagefright_soft_mp3dec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_foundation.so:system/lib/libstagefright_foundation.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_aacenc.so:system/lib/libstagefright_soft_aacenc.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_flacenc.so:system/lib/libstagefright_soft_flacenc.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_avc_common.so:system/lib/libstagefright_avc_common.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_enc_common.so:system/lib/libstagefright_enc_common.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_ffmpegaudiodec.so:system/lib/libstagefright_soft_ffmpegaudiodec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_ffmpegvideodec.so:system/lib/libstagefright_soft_ffmpegvideodec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_amrwbenc.so:system/lib/libstagefright_soft_amrwbenc.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_amrdec.so:system/lib/libstagefright_soft_amrdec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright.so:system/lib/libstagefright.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_h264enc.so:system/lib/libstagefright_soft_h264enc.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_mpeg4enc.so:system/lib/libstagefright_soft_mpeg4enc.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_amrnb_common.so:system/lib/libstagefright_amrnb_common.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_h264dec.so:system/lib/libstagefright_soft_h264dec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_vpxdec.so:system/lib/libstagefright_soft_vpxdec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_amrnbenc.so:system/lib/libstagefright_soft_amrnbenc.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_vorbisdec.so:system/lib/libstagefright_soft_vorbisdec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_aacdec.so:system/lib/libstagefright_soft_aacdec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_soft_ddpdec.so:system/lib/libstagefright_soft_ddpdec.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_omx.so:system/lib/libstagefright_omx.so \
 $(LOCAL_PATH)/proprietary/system/lib/libstagefright_yuv.so:system/lib/libstagefright_yuv.so \
 $(LOCAL_PATH)/proprietary/system/lib/libmediaplayerservice.so:system/lib/libmediaplayerservice.so \
 $(LOCAL_PATH)/proprietary/system/lib/libcamera_core.so:system/lib/libcamera_core.so \
 $(LOCAL_PATH)/proprietary/system/lib/libcamera_scalado.so:system/lib/libcamera_scalado.so \
 $(LOCAL_PATH)/proprietary/system/lib/libimageinfo.so:system/lib/libimageinfo.so \
 $(LOCAL_PATH)/proprietary/system/lib/libgnuexif.so:system/lib/libgnuexif.so \
 $(LOCAL_PATH)/proprietary/system/lib/libRedEye.so:system/lib/libRedEye.so \
 $(LOCAL_PATH)/proprietary/system/lib/libhelixplayer.so:system/lib/libhelixplayer.so \
 $(LOCAL_PATH)/proprietary/system/lib/libwvm.so:system/lib/libwvm.so \
 $(LOCAL_PATH)/proprietary/system/lib/libdolbyaudioeffectnativeservice.so:system/lib/libdolbyaudioeffectnativeservice.so \
 $(LOCAL_PATH)/proprietary/system/lib/libdolbymobileaudioeffect_jni.so:system/lib/libdolbymobileaudioeffect_jni.so \
 $(LOCAL_PATH)/proprietary/system/lib/libril.so:system/lib/libril.so \
 $(LOCAL_PATH)/proprietary/system/lib/libxgold-ril.so:system/lib/libxgold-ril.so \
 $(LOCAL_PATH)/proprietary/system/lib/libhuawei-audio-ril.so:system/lib/libhuawei-audio-ril.so \
 $(LOCAL_PATH)/proprietary/system/lib/libfm_hal.so:system/lib/libfm_hal.so \
 $(LOCAL_PATH)/proprietary/system/lib/libfm_volume.so:system/lib/libfm_volume.so \
 $(LOCAL_PATH)/proprietary/system/lib/egl/libEGL_VIVANTE.so:system/lib/egl/libEGL_VIVANTE.so \
 $(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv1_CM_VIVANTE.so:system/lib/egl/libGLESv1_CM_VIVANTE.so \
 $(LOCAL_PATH)/proprietary/system/lib/egl/libGLESv2_VIVANTE.so:system/lib/egl/libGLESv2_VIVANTE.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio.a2dp.default.so:system/lib/hw/audio.a2dp.default.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio.primary.k3v2oem1.so:system/lib/hw/audio.primary.k3v2oem1.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/audio_policy.default.so:system/lib/hw/audio_policy.default.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/camera.k3v2oem1.so:system/lib/hw/camera.k3v2oem1.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/copybit.huawei.so:system/lib/hw/copybit.huawei.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/gps.k3v2oem1.so:system/lib/hw/gps.k3v2oem1.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/gralloc.huawei.so:system/lib/hw/gralloc.huawei.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/hwcomposer.huawei.so:system/lib/hw/hwcomposer.huawei.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/libbcmfm_if.so:system/lib/hw/libbcmfm_if.so \
 $(LOCAL_PATH)/proprietary/system/lib/hw/sensors.k3v2oem1.so:system/lib/hw/sensors.k3v2oem1.so \
 $(LOCAL_PATH)/proprietary/system/lib/soundfx/libdolbymobileeffect.so:system/lib/soundfx/libdolbymobileeffect.so
